//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilePlatform.SendMessage {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendMessage.mobileSoap")]
    public interface mobileSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 desaddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendmessage", ReplyAction="*")]
        MobilePlatform.SendMessage.sendmessageResponse sendmessage(MobilePlatform.SendMessage.sendmessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendmessage", ReplyAction="*")]
        System.Threading.Tasks.Task<MobilePlatform.SendMessage.sendmessageResponse> sendmessageAsync(MobilePlatform.SendMessage.sendmessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendmessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendmessage", Namespace="http://tempuri.org/", Order=0)]
        public MobilePlatform.SendMessage.sendmessageRequestBody Body;
        
        public sendmessageRequest() {
        }
        
        public sendmessageRequest(MobilePlatform.SendMessage.sendmessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendmessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string desaddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string send_user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string send_system;
        
        public sendmessageRequestBody() {
        }
        
        public sendmessageRequestBody(string desaddr, string msg, string send_user, string send_system) {
            this.desaddr = desaddr;
            this.msg = msg;
            this.send_user = send_user;
            this.send_system = send_system;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendmessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendmessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public MobilePlatform.SendMessage.sendmessageResponseBody Body;
        
        public sendmessageResponse() {
        }
        
        public sendmessageResponse(MobilePlatform.SendMessage.sendmessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendmessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendmessageResult;
        
        public sendmessageResponseBody() {
        }
        
        public sendmessageResponseBody(bool sendmessageResult) {
            this.sendmessageResult = sendmessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mobileSoapChannel : MobilePlatform.SendMessage.mobileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mobileSoapClient : System.ServiceModel.ClientBase<MobilePlatform.SendMessage.mobileSoap>, MobilePlatform.SendMessage.mobileSoap {
        
        public mobileSoapClient() {
        }
        
        public mobileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mobileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mobileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mobileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobilePlatform.SendMessage.sendmessageResponse MobilePlatform.SendMessage.mobileSoap.sendmessage(MobilePlatform.SendMessage.sendmessageRequest request) {
            return base.Channel.sendmessage(request);
        }
        
        public bool sendmessage(string desaddr, string msg, string send_user, string send_system) {
            MobilePlatform.SendMessage.sendmessageRequest inValue = new MobilePlatform.SendMessage.sendmessageRequest();
            inValue.Body = new MobilePlatform.SendMessage.sendmessageRequestBody();
            inValue.Body.desaddr = desaddr;
            inValue.Body.msg = msg;
            inValue.Body.send_user = send_user;
            inValue.Body.send_system = send_system;
            MobilePlatform.SendMessage.sendmessageResponse retVal = ((MobilePlatform.SendMessage.mobileSoap)(this)).sendmessage(inValue);
            return retVal.Body.sendmessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MobilePlatform.SendMessage.sendmessageResponse> MobilePlatform.SendMessage.mobileSoap.sendmessageAsync(MobilePlatform.SendMessage.sendmessageRequest request) {
            return base.Channel.sendmessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<MobilePlatform.SendMessage.sendmessageResponse> sendmessageAsync(string desaddr, string msg, string send_user, string send_system) {
            MobilePlatform.SendMessage.sendmessageRequest inValue = new MobilePlatform.SendMessage.sendmessageRequest();
            inValue.Body = new MobilePlatform.SendMessage.sendmessageRequestBody();
            inValue.Body.desaddr = desaddr;
            inValue.Body.msg = msg;
            inValue.Body.send_user = send_user;
            inValue.Body.send_system = send_system;
            return ((MobilePlatform.SendMessage.mobileSoap)(this)).sendmessageAsync(inValue);
        }
    }
}
